docs: update `e2eTests/README.md`
ELIXIR-NO/FEGA-Norway pull request #148
Opened 2024-05-07 14:18 UTC by yasinmiran

2024-05-07 14:47 UTC, joshbaskaran requested changes

2024-05-07 14:47 UTC, joshbaskaran commented on e2eTests/README.md
>     - `sudo apt install openjdk-21-jdk`
```suggestion
4. [Install Java](https://adoptium.net/installation/)
```

2024-05-10 14:35 UTC, yasinmiran commented on e2eTests/README.md
>     - `sudo apt install openjdk-21-jdk`
Fixed with [317a210](https://github.com/ELIXIR-NO/FEGA-Norway/pull/148/commits/317a210b1a7dfcf519a216bd93a4c41870adc416)

2024-05-10 15:03 UTC, joshbaskaran approved these changes

2024-05-14 06:59 UTC, merged