Add README for MQ-interceptor
ELIXIR-NO/FEGA-Norway pull request #295
Opened 2024-11-15 09:17 UTC by kjetilkl

2024-11-15 10:04 UTC, Parisa68 commented on services/mq-interceptor/README.md
> +The MQ-interceptor solves both of these problem by performing the following tasks:
problems

2024-11-15 12:32 UTC, kjetilkl commented on services/mq-interceptor/README.md
> +The MQ-interceptor solves both of these problem by performing the following tasks:
Fixed!

2024-11-15 15:52 UTC, Parisa68 approved these changes

2024-11-22 12:26 UTC, kjellp requested changes
Looks good, please fix recommended capitalization fix before merging,

2024-11-22 12:26 UTC, kjellp commented on services/mq-interceptor/README.md
> +The MQ-interceptor is written in the [GO language](https://go.dev/) and requires the [GO compiler](https://go.dev/doc/install) to build.
```suggestion
The MQ-interceptor is written in the [Go language](https://go.dev/) and requires the [Go compiler](https://go.dev/doc/install) to build.
```

2024-11-22 12:27 UTC, pavelvazquez submitted a review, later dismissed

2024-11-22 12:27 UTC, pavelvazquez commented on services/mq-interceptor/README.md
> +| VERIFY_CERT | If this is set to FALSE, the client will not verify the servers’ certificate chain and host name and will thus accept any certificate presented by the server and any host name in that
```suggestion
| VERIFY_CERT | If this is set to FALSE, the client will not verify the server’s certificate chain and host name and will thus accept any certificate presented by the server and any host name in that certificate. This should only be set to FALSE for testing purposes. |
```

2024-11-22 12:27 UTC, pavelvazquez commented on services/mq-interceptor/README.md
> +| VERIFY_CERT | If this is set to FALSE, the client will not verify the servers’ certificate chain and host name and will thus accept any certificate presented by the server and any host name in that
I believe in a single server

2024-11-22 12:28 UTC, kjetilkl commented on services/mq-interceptor/README.md
> +| VERIFY_CERT | If this is set to FALSE, the client will not verify the servers’ certificate chain and host name and will thus accept any certificate presented by the server and any host name in that
There are two servers

2024-11-22 12:33 UTC, pavelvazquez approved these changes

2024-11-22 12:34 UTC, kjellp approved these changes

2024-11-22 12:35 UTC, merged